import "./globals.css";
import { Poppins } from "next/font/google";
import AppNavbar from "@/components/common/Navbar";
import AppFooter from "@/components/common/Footer";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppNavbar />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
